# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Wandering in the random forest
subtitle: "My journey into data science"
site.description: "The fun part of data science is getting your hands dirty, from preprocessing data, to training your model. The way to get there, however is not easy. I hope, that by sharing my experience, you can avoid learning the hard way! :)" 

name: "Boglarka Racz"
teaser: /assets/images/lightbulb.png
github_username:  rbogi
linkedin_username: boglarka-racz


remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "contrast" 

repository: "rbogi/rbogi.github.io" 
markdown: kramdown
locale: "en-US" 
include: ["_pages"]
search: true
og_image: /assets/images/lightbulb.png




plugins:
  - jekyll-feed
  - jekyll-include-cache 
  

author:
  name     : "Boglarka Racz"
  avatar   : "/assets/images/lightbulb.png"
  bio      : "Economist by education, data scientist at heart. Currently studying Medical Informatics, looking for challenges and to have some fun with machine learning."
  location : "Basel, Switzerland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rbogi"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/boglarka-racz"
  
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/boglarka-racz"  
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rbogi"

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"


defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      author_profile: true

